changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
url=jdbc:postgresql://localhost:5434/task_manager
username=task_manager
password=task_manager
referenceUrl=hibernate:spring:com.example.task_manager.models?dialect=org.hibernate.dialect.PostgreSQLDialect&hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
diffTypes=tables,columns,foreignkeys,sequences
diffChangeLogFile=src/main/resources/db/changelog/changes/new-changelog.xml
